### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by ValentinWalter** [rberenguel/bear-note-graph#4]
0.1.4
```
INFO - Copying Bear database to /tmp/BearExportTemp.sqlite
INFO - Fetching notes from (the copy of the) database
INFO - Fetched 343 notes from the (copy of) the Bear database
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/bear-note-graph", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bear_note_graph/main.py", line 121, in main
    generate_graph(graph_format)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bear_note_graph/generate.py", line 45, in generate_graph
    all_tags, all_notes, all_tag_edges, all_note_edges = generate_graph_from_rows(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bear_note_graph/generate.py", line 76, in generate_graph_from_rows
    if len(md_text) < 3:
TypeError: object of type 'NoneType' has no len()
```

**Comment by rberenguel** [comment]
@ValentinWalter thanks! This one is... interesting: I'll add a try catch here and if possible create a link to the note so you can have a look, but how can a note exist without text? I was expecting text to be a required property of the note :D I will not assume the notes exist in any expected shape I guess!

**Comment by ValentinWalter** [comment]
Yeah, that's the thing with assumptions, the world is just too messy 😅 No need for the link though, I just went through the the SQLite database and actually found multiple notes with no text. From a first glance, it seems there's two different cases. 
* One is that locked notes never have text, but they do have a title. 
* Then there were those with no text and no title. I looked them up by their UUID, and it turns out I had some empty notes (those "A wonderful new note" notes you get when creating a new note) in the trash.

**Comment by ValentinWalter** [comment]
A clean fix might be to see if the note is locked via `ZENCRYPTED` and then just work with the title and UUID. For unencrypted empty notes, simply ignoring them and then having something like
```
INFO - Ignoring 4 empty notes from (the copy of) the Bear database
```
should be both good UX and easy to implement. I don't know Python too well, but I might just try myself at a PR :)

**Comment by rberenguel** [comment]
Oh, I don't have locked notes so this explains it. I should have thought of that one1 Empty notes (the wonderful new note kind) are already skipped with the "len" there (they have an empty string as text, so it's "fine" for the code as is... I keep one just in case to make sure I don't regress on the code). Thanks a lot for the dig down, this will help me a lot to add some test cases and purge a bit the assumptions.

**Comment by rberenguel** [comment]
@ValentinWalter _hopefully_ this is fixed in 0.1.8 (I botched 0.1.5 due to the type of encrypted, int not string ¯\﹍(ツ)﹍/¯) If a note has no text now it will be logging it into the console but move along, likewise for title and the other cases. If it's encrypted (checking the zencrypted field) it will add a lock to the title (since it can still be linked in another note, something I had wrong in 0.1.6...). And 0.1.7 lost the ability to exclude certain titles (at least now I have a regression test for this one, when I said I needed more test it ain't a joke)

Probably there are still a few edge cases, but hopefully you don't hit any more and can enjoy your note graph :)

**Comment by ValentinWalter** [comment]
Hmm, it's still showing the original error. `pip list` shows me that it's indeed 0.1.8. I've had a quick glance over your tests and it seems like you're injecting an empty string, but in my case it's a `NoneType`. I don't know Python too well, but if that's the equivalent of `nil` in Swift or `null` in JavaScript, then that might be the problem. The empty string still has the `len()` method, but a `NoneType` does not. Could that be it?

**Comment by rberenguel** [comment]
That's strange, for that test I'm injecting a dictionary with no `md_text` field: https://github.com/rberenguel/bear-note-graph/blob/master/tests/test_regressions.py#L56 (to be fair this test is probably testing too much by checking two things at once) and the line in question that is doing the check should be this one: https://github.com/rberenguel/bear-note-graph/blob/master/bear_note_graph/generate.py#L115

I'm guessing that since you are still seeing the error, the SQLite connector is passing None, explicitly, instead of not passing the named column in the row, as was my assumption. I'll add a check and test for that, should be out in a couple minutes (I got efficient at publishing :D )

**Comment by rberenguel** [comment]
<img width="654" alt="image" src="https://user-images.githubusercontent.com/2410938/79909032-96130100-841c-11ea-8a2b-5f63eb0da6c4.png">

Proper reproduction now! I had been blindsided from reading your error message too quickly and thinking "ah, I know what that is". Now it's (in addition to checking the keys, which shouldn't hurt) checking that the text (which we run len on) is not None. Hopefully titles can't be none, because I also do some length process (adding ellipsis). 0.1.9 is out now (or in a few minutes depending on pypi speed to spread)

**Comment by ValentinWalter** [comment]
Perfect 👍 (aside from some [stupid mistake](https://github.com/rberenguel/bear-note-graph/issues/5) on my part)

[Here's my graph](https://github.com/rberenguel/bear-note-graph/files/4512817/bear_graph_anonomyse.pdf) if you're interested. I love this kinda stuff, many thanks for creating this!

**Comment by rberenguel** [comment]
I love it, looks like you properly link your notes (unlike myself). And glat to see the anonymise option being used :)

Thanks a lot for your help in improving it so more people can use it
